import type { Metadata } from "next";
import "./globals.css";
import { MusicProvider } from "@/utils/music";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ fontFamily: "var(--font-noto-serif)" }}>
        <Suspense fallback={<div>Loading...</div>}>
          <MusicProvider>
            {children}
          </MusicProvider>
        </Suspense>
      </body>
    </html>
  );
}
